# Travis continuous integration for kitodo-production

language: java

jdk:
  - oraclejdk7
  - openjdk7

addons:
  apt:
    packages:
      - tomcat7-common

cache:

env:

script: ant -lib /usr/share/tomcat7/lib all
