# Travis continuous integration for Kitodo.Production

language: java

jdk:
  - oraclejdk7
  - openjdk7

addons:
  apt:
    packages:
      - ant-optional
      - tomcat7-common

cache:

env:

script: ant -lib /usr/share/tomcat7/lib all
