# Travis continuous integration for kitodo-production

language: java

cache:

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

sudo: required

env: DB=mysql

services:
  - mysql

script: mvn clean install -Pall-tests,flyway,checkstyle-findbugs

before_install:

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp Kitodo-DataManagement/src/main/resources/db/config/flyway.properties.travis Kitodo-DataManagement/src/main/resources/db/config/flyway.properties
  - mysql -u root -e 'CREATE DATABASE kitodo;'
  - mysql -u root -e "CREATE USER 'kitodo'@'localhost' IDENTIFIED BY 'kitodo';"
  - mysql -u root -e "GRANT ALL ON kitodo.* TO 'kitodo'@'localhost';"
  - mysql -u root kitodo < Kitodo/setup/schema.sql
  - mkdir -p '/usr/local/kitodo/plugins'
